(let* ((buffers (buffer-list))
       (buffer-count (length buffers)))
  (erase-c-messages)
  (erase-messages)
  (c-message-open "%s open buffers" buffer-count)
  (mapc #'(lambda (buf)
            (c-message "- %S" buf))
        buffers)
  )
