(defun align-backslash-eol-widest-region(beg end)
  (interactive "*r")
  (erase-c-messages)
  (c-message-open)
  (let ((furthest-backslash-col 0) (outer-action nil))
    (save-match-data
      (save-mark-and-excursion
        (goto-char beg)
        (beginning-of-line)
        (setq outer-action
              (catch 'read-break
                (while (re-search-forward "^.*?[^\\]+\\s-+\\([\\]\\)\\s-*$" end t)
                  (goto-char (match-beginning 1))
                  (let* (
                         (action nil)
                         (tmp nil)
                         (pos-beg (point))
                         (pos-end (progn (end-of-line) (point)))
                         (text  (buffer-substring-no-properties pos-beg pos-end))
                         (attempts (list))
                         )
                    (c-message "pos-beg: %S" pos-beg)
                    (c-message "pos-end: %S" pos-end)
                    (c-message "text: %S" text)
                    (c-message "action: %S" action)
                    (c-message "attempts: %S" attempts)
                    (c-message "outer-action: %S" outer-action)
                    (c-message "")

                    (while (null action)
                      (setq tmp (downcase (string-trim (read-string "[b]reak/[n]ext/[c]ontinue: "))))
                      (push tmp attempts)
                      (cond nil
                            ((or (string= tmp "break")
                                 (string= tmp "b"))
                             (throw 'read-break tmp))

                            ((or (string= tmp "continue")
                                 (string= tmp "c")
                                 (string= tmp "next")
                                 (string= tmp "n")
                                 )
                             ;; (throw 'read-break tmp))
                             (setq action "continue"))
                            )
                      )
                    (forward-line)
                    (beginning-of-line)
                    )
                  )
                ); end (catch ...)
              ); end (setq action (catch ...))
        ) ;; ends (save-mark-and-excursion ...)
      ) ;; ends (save-match-data ...)
    )
  )
