;;;defadvice
;;;defalias
;;;defclass
;;;defconst
;;;defconst-mode-local
;;;defcustom
;;;defcustom-c-stylevar
;;;defface
;;;defgroup
;;;defimage
;;;defmacro
;;;defmath
;;;defsubst
;;;deftheme
;;;defun
;;;defun-declarations-alist
;;;defun-markdown-buffer
;;;defun-markdown-ref-checker
;;;defun-prompt-regexp
;;;defvar
;;;defvar-keymap
;;;defvar-local
;;;defvar-mode-local
;;;defvaralias
