(let* (
       (timestamp-string (format-time-string "%s"))
       (timestamp-int (string-to-number timestamp-string))
       (float-time-ret (float-time))
       (int-time (truncate float-time-ret))
       (current-time-ret (current-time))
       (time-convert-ret (time-convert current-time-ret 'integer)))
  (erase-c-messages)
  (c-message-open "")
  (c-message "(timestamp-string): %S" timestamp-string)
  (c-message "(timestamp-int): %S" timestamp-int)
  (c-message "(float-time): %S" float-time-ret)
  (c-message "(truncate (float-time)): %S" int-time)
  (c-message "(current-time): %S" current-time-ret)
  (c-message "(time-convert (current-time) 'integer): %S" time-convert-ret))
