(progn
  (require 'package)
  (require 'flycheck)
  (line-number-mode t)
  (setq global-package-online nil) ;; set to non-nil to enable
  (setq global-flycheck-mode t)
  (setq debug-on-error nil)
  (setq initial-scratch-message nil)
  (setq auto-save-interval 137)
  ;; (setq case-fold-search t)
  (defalias 'yes-or-no-p 'y-or-n-p)
  (defalias 'describe 'describe-symbol)
  )
(add-to-list 'custom-safe-themes "5bd001a0f95d54174370e9275b1f594829930a1a95ed82741a5492facb7415e7")
(set-face-attribute 'default nil :font "JetBrains Mono-21")
(load-library "ui")
(load-library "functions")
(load-library "g-modeline")
(load-library "keys")
(load-library "modes")
(load-library "hooks")
(load-library "macros")
(load-library "pest-mode")
(load-library "functions")
(load-library "elpamelpa")
;; (load-library "ninja-mode")
;; (load-library "cobol-mode")
;; (load-library "cmake-mode")
;; (load-library "visual-basic-mode")
(defun $/load-library () "." (interactive) (load-library "k"))
(defun $/load-init ()
  "."
  (interactive)
  (load-file "~/.emacs.d/init.el"))
(defvar $/keymap (copy-keymap global-map))
($/paint-mode-line)
(defalias 'plus #'+)
(defalias 'quotient #'/)
(defalias 'times #'*)
(defalias 'difference #'-)
(line-number-mode)
