(require 'package)
(require 'flycheck)
(line-number-mode t)
;; (setq package-archives nil)
(setq global-flycheck-mode t)
(with-eval-after-load 'flycheck
  (require 'flycheck-pest)
  (flycheck-pest-setup))

(require 'web-mode)
(require 'company)
(require 'go-mode)
(require 'jinja2-mode)
(require 'toml)
(require 'protobuf-mode)
(if (runtime-is-osx)

    (require 'python-mode)
  )
(require 'elixir-mode)
(require 'terraform-mode)
(require 'toml-mode)
(require 'rust-mode)
(require 'yaml-mode)
(require 'dockerfile-mode)
(require 'jsonnet-mode)
(require 'typescript-mode)
(require 'whitespace)
(require 'blacken)
(require 'make-mode)
(require 'ibuffer)
(require 'calendar)
(require 'rect)
(require 'compile)
(require 'ert)

(setq python-indent-offset 6)
(setq company-idle-delay 0)
(setq company-show-quick-access t)

(setq large-file-warning-threshold 9000000 make-backup-files nil)
(setq rust-format-on-save nil rust-rustfmt-bin "~/.cargo/bin/rustfmt" rust-rustfmt-switches '("--edition" "2021" "--color" "always" "--unstable-features"))

(setq replace-regexp-lax-whitespace t case-fold-search nil)


(setq inhibit-local-variables-regexps (append '("\\[.]sh" "\\[.]json\w?" "\\[.][tj]sx?") inhibit-local-variables-regexps ))
;;(setq line-number-display-limit 10000)
;; ;; ;; *;; ;; OzsgOzsgOzsqOzsgOzsgKGRlZnVuIHNldHVwLXRpZGUtbW9kZSAoKSAoaW50ZXJhY3RpdmUpIDs7ICh0aWRlLXNldHVwKSAoZmx5Y2hlY2stbW9kZSArMSkgKHNldHEgZmx5Y2hlY2stY2hlY2stc3ludGF4LWF1dG9tYXRpY2FsbHkgJyhzYXZlIG1vZGUtZW5hYmxlZCkpIChlbGRvYy1tb2RlICsxKSA7OyAodGlkZS1obC1pZGVudGlmaWVyLW1vZGUgKzEpIChjb21wYW55LW1vZGUgKzEpKTs7IDs7IDs7Kjs7IDs7IChhZGQtaG9vayAnYmVmb3JlLXNhdmUtaG9vayAndGlkZS1mb3JtYXQtYmVmb3JlLXNhdmUpIDs7IDs7IDs7Kjs7IDs7IChhZGQtaG9vayAndHlwZXNjcmlwdC1tb2RlLWhvb2sgIydzZXR1cC10aWRlLW1vZGUpIDs7IDs7IDs7Kjs7IDs7IChhZGQtaG9vayAnd2ViLW1vZGUtaG9vayAgKGxhbWJkYSAoKSAgKHdoZW4gKHN0cmluZy1lcXVhbCAianN4IiAoZmlsZS1uYW1lLWV4dGVuc2lvbiBidWZmZXItZmlsZS1uYW1lKSkgIChzZXR1cC10aWRlLW1vZGUpKSkpIChhZGQtaG9vayAnd2ViLW1vZGUtaG9vayAgKGxhbWJkYSAoKSAgKHdoZW4gKHN0cmluZy1lcXVhbCAidHN4IiAoZmlsZS1uYW1lLWV4dGVuc2lvbiBidWZmZXItZmlsZS1uYW1lKSkgIChzZXR1cC10aWRlLW1vZGUpKSkp
(setq vc-handled-backends nil)
(eval-after-load "vc" '(remove-hook 'find-file-hook 'vc-find-file-hook))


(setq kill-ring-max #xffffff
      company-tooltip-align-annotations t
      rust-cargo-default-arguments " --offline "
      web-mode-engines-alist '(("jsx"  . "\\.[tj]sx?"))
      typescript-indent-level 2
      web-mode-part-padding 0
      web-mode-enable-auto-quoting 'nil
      web-mode-auto-quote-style 3
      web-mode-content-types-alist
      '(("json" . "\\.jsonp?'")
        ("html"  . "html'")
        ("jsx"  . "\\.[tj]sx\\'"))
      )
; (add-to-list 'magic-mode-alist '("^#!/usr/bin/\\(env\\s-+.*\\)?\\(python\\)" . python-mode))
; (add-to-list 'magic-mode-alist '("^#!/usr/bin/\\(env\\s-+.*\\)?\\(ba\\)?sh\\)" . shell-script-mode))

(setq whitespace-style 'empty)
(setq web-mode-content-types-alist
      '(("json" . ".*[.]json$'")
        ("jsx"  . ".*[.]jsx")))
;; (flycheck-define-checker sh-shellcheck :command ("shellcheck" "-x" "-f" "checkstyle" "-s" (eval (symbol-name sh-shell)) source) :modes shell-script-mode :error-parser flycheck-parse-checkstyle)


(list
  '("/shell[.]d/" . shell-script-mode)
  '("/bash_completion\\([.]d\\)?/" . shell-script-mode)
  '("/opt[\/]libexec/" . shell-script-mode)
  '("/bin/py/[^/.]*" . python-mode)
  '("/bin/sh/[^/.]*" . shell-script-mode)
  '("/bin/[^/.]*" . shell-script-mode)
  '("Dockerfile.*" . dockefile-mode)
  '("Makefile[.].*" . makefile-mode)
  '("Pipfile" . toml-mode)
  '("pyproject.toml" . toml-mode)
  '("Pipfile.lock" . toml-mode)
  '("\\.babelrc" . web-mode)
  '("\\.bash$" . shell-script-mode)
  '("/workbench/[0-9-]+/[^/]*bash[^/]*$" . shell-script-mode)
  '("\\.bashrc$" . shell-script-mode)
  '("\\.c?js$" . web-mode)
  '("\\.erl$" . erlang-mode)
  '("\\.j2$" . jinja2-mode)
  '("\\.tera$" . jinja2-mode)
  '("\\.json$" . web-mode)
  '("\\.prettierrc$" . web-mode)
  '("\\.json-*$" . web-mode)
  '("\\.jsonnet$" . jsonnet-mode)
  '("\\.m?jsx?$" . web-mode)
  '("\\.libsonnet$" . jsonnet-mode)
  '("\\.php$" . php-mode)
  '("\\.plist$" . xml-mode)
  '("\\.proto$" . protobuf-mode)
  '("\\.rs$" . rust-mode)
  '("\\.noon$" . rust-mode)
  '("\\.sh$" . shell-script-mode)
  '("\\.shell$" . shell-script-mode)
  '("\\.swift$" . swift-mode)
  '("\\.reb$" . reb-mode)
  '("\\.tf$" . terraform-mode)
  '("\\.toml$" . toml-mode)
  '("\\.ts$" . typescript-mode)
  '("\\.brs$" . brightscript-mode)
  '("\\.sed$" . sed-mode)
  '("\\.g?awk$" . awk-mode)
  '("\\.tsx$" . web-mode)
  '("\\.typ?$" . typst-mode)
  '("\\.el\(\\.gz\)?$" . emacs-lisp-mode)
  '("\\.ya?ml$" . yaml-mode)
  '("^---$" . yaml-mode)
  '("nginx.conf$" . nginx-mode)
  '("[.][a-z]\{3,\}[a-z_-]+rc$" . conf-mode)
  '("\\.lua$" . lua-mode)
  '("\\.frm$" . visual-basic-mode)
  '("\\.vbp$" . visual-basic-mode)
  '("\\.pest$" . pest-mode)
  '("\\.erb\\'" . web-mode)
  '("\\.mustache\\'" . web-mode)
  '("\\.djhtml\\'" . web-mode)
  '("\\.html?\\'" . web-mode)
  '("\\.md$" . markdown-mode)
  '("\\.c?j$" . web-mode)
  '("\\.er$" . erlang-mode)
  '("\\.j$" . jinja2-mode)
  '("\\.jso$" . web-mode)
  '("\\.json-$" . web-mode)
  '("\\.jsonne$" . jsonnet-mode)
  '("\\.m?jsx$" . web-mode)
  '("\\.libsonne$" . jsonnet-mode)
  '("\\.libsonnet$" . jsonnet-mode)
  '("\\.ph$" . php-mode)
  '("\\.plis$" . xml-mode)
  '("\\.prot$" . protobuf-mode)
  '("\\.r$" . rust-mode)
  '("\\.noo$" . rust-mode)
  '("\\.s$" . shell-script-mode)
  '("\\.shel$" . shell-script-mode)
  '("\\.swif$" . swift-mode)
  '("\\.t$" . terraform-mode)
  '("\\.tom$" . toml-mode)
  '("\\.t$" . typescript-mode)
  '("\\.ts$" . web-mode)
  '("\\.typ$" . typst-mode)
  '("\\.ya?m$" . yaml-mode)
  )
 )
))
