(defun goto-next-token (token-char token-count &optional beg-pos)
  "."
  (unless (eq (length token-char) 1)
    (error "token-char is should have length 1 but is %s" (length token-char)))
  (unless (integerp (or token-count (point)))
    (error "token-count is should be a number not \"%s\"" token-count))
  (unless (integerp (or beg-pos (point)))
    (error "beg-pos is should be a number not \"%s\"" beg-pos))

  (if (not (eq beg-pos (point)))
    (goto-char beg-pos))
  ;; (setq case-fold-search nil)
  (let* (
         (case-fold-search nil)
         (token-regexp (regexp-quote token-char))
         (token-count 0)
         (beg-pos (or beg-pos (point)))
         (pos beg-pos)
         (token-pos beg-pos)
         (marker (point-marker)))
    (re-search-forward token-regexp nil t)
    (setq beg-pos (match-beginning 0))
    (if (> (match-beginning 0) pos)
      (setq token-count (+ token-count 1))
      (setq token-pos (match-beginning 0))
      (re-search-forward token-regexp nil t)
      (if (> (match-beginning 0) token-pos)
        (setq pos token-pos)
        (setq token-pos (match-beginning 0))
        (setq token-pos (match-beginning 0))))
    (setq end-pos (match-end 0))
    '(
      ("beg-pos" . beg-pos)
      ("token-pos" . token-pos)
      ("token-count" . token-count)
      ("end-pos" . end-pos))))

;; (defun goto-next-closing-token (open-token open-count close-token &optional beg-pos)
;;   "."
;;   (unless (eq (length open-token) 1)
;;     (error "open-token is should have length 1 but is %s" (length open-token)))
;;   (unless (eq (length close-token) 1)
;;     (error "close-token is should have length 1 but is %s" (length close-token)))
;;   (unless (integerp (or open-count (point)))
;;     (error "open-count is should be a number not \"%s\"" open-count))
;;   (unless (integerp (or beg-pos (point)))
;;     (error "beg-pos is should be a number not \"%s\"" beg-pos))

;;   ;; (setq case-fold-search nil)
;;   (let* (
;;          (case-fold-search nil)
;;          (open-regexp (regexp-quote open-token))
;;          (close-regexp (regexp-quote close-token))
;;          (open-count 0)
;;          (close-count 0)
;;          (beg-pos (or beg-pos (point)))
;;          (pos beg-pos)
;;          (open-pos beg-pos)
;;          (close-pos beg-pos)
;;          (marker (point-marker))
;;          )
;;     (re-search-forward open-regexp nil t)
;;     (setq beg-pos (match-beginning 0))
;;     (if (> (match-beginning 0) pos)
;;       (setq open-count (+ open-count 1))
;;       (setq open-pos (match-beginning 0))
;;       (re-search-forward open-regexp nil t)
;;       (if (> (match-beginning 0) open-pos)
;;           (setq pos open-pos)
;;           (setq open-pos (match-beginning 0))
;;           (setq open-pos (match-beginning 0))
;;           )
;;       )
;;     (setq end-pos (match-end 0))

;;     ;; (while (> (match-beginning 0) pos)
;;     ;;   (setq close-count (+ close-count 1))
;;     ;;   (setq close-pos (match-beginning 0))
;;     ;;   (re-search-forward close-regexp nil t)
;;     ;;   (if (> (match-beginning 0) close-pos)
;;     ;;       (setq pos close-pos)
;;     ;;       (setq close-pos (match-beginning 0))
;;     ;;       )
;;     ;;   )
;;     '(
;;       ("beg-pos" . beg-pos)
;;       ("open-pos" . open-pos)
;;       ("open-count" . open-count)
;;       ("end-pos" . end-pos)
;;     )
;;   )
