(defun Ox33b4O/$/mode-line-foreground ()  "#FF1978") ;; #F13976
(defun Ox33b4O/$/mode-line-background () "#3d3d3d")
(defun Ox33b4O/$/mark-indicator-color() "#cad79d")
(defun Ox33b4O/$/mode-line-arrow-right() " ⇒ ")
(defun Ox33b4O/$/mode-line-arrow-left() " ⇐ ")

(defun $$$$$$$$()
  "."
  (interactive)

  (let* (($font-name$               (font-name-for-system))
         ($sel$                     "#C6DCFC")
	 ($sel$                     "#CFC6A6")
         ($background$              "#1C1C1C")
         ($variable$                "#F49101")
         ($string$                  "#DCDC88")
         ($regexp$                  "#C63367")
         ($admonition$              "#F80101")
         ($admonition$              "#F937B9")
         ($warning$                 "#F80101")
         ($error$                   "#DB5045")
         ($operators$               "#F682FF")
         ($number$                  "#FC580C")
         ($normal$                  "#DEDEDE")
         ($mode-line-inactive-bg$   "#211F17")
         ($mode-line-inactive-bg$   "#312F27")
         ($mode-line-inactive-fg$   "#A66A00")
         ($method-declaration$      "#A6E22E")
         ($type-face$               "#36F6E9")
         ($type-face$               "#1996C9")
         ($line-fg$                 "#919588")
         ($line-number$             "#161A1F")
         ($current-line-number$     "#A66A00")
         ($current-line-number$     "#F6CA51")
         ($keywords$                "#F13976")
         ($current-line$            "#151515")
         ($operators$               "#F479C4")
         ($operators$               "#79B9Ff")
         ($operators$               "#EF5AAA")
         ($constant$                "#FF79C6")
         ($comments$                "#A79C83")
	 ($sel$                     "#F5BF08")
         ($cursor$                  $sel$))

    (line-number-mode nil)
    (require 'make-mode)
    (require 'ibuffer)
    (require 'calendar)
    (require 'rect)
    (require 'compile)
    (require 'tramp-cmds)
    (setq ns-allow-anti-aliasing t)
    (setq ns-function-modifier 'control)
    (setq ns-option-modifier 'meta)
    (setq ns-command-modifier 'meta)

    (show-paren-mode 10)
    (setq-default indent-tabs-mode nil)
    (setq-default truncate-lines t)
    (global-font-lock-mode 1)
    (transient-mark-mode 1)
    (tramp-cleanup-all-connections)

    (set-face-attribute 'default nil :font $font-name$)
    (set-face-attribute 'info-menu-header nil :foreground "#DB5045" :underline nil :bold t :font $font-name$)
    (global-prettify-symbols-mode 0)
    (setq linum-format "%6d")
    (display-line-numbers-mode t)
    ;; (setq display-line-numbers-major-tick 0)
    ;; (setq display-line-numbers-minor-tick 0)
    (set-face-attribute 'cursor nil :background $cursor$ :foreground $cursor$)
    (setq-default cursor-type (cursor-type-for-system))
    (set-face-attribute 'Info-quoted nil :bold nil :background $background$ :foreground $normal$ )
    (set-face-attribute 'bold nil        :bold t :background $background$ :foreground $normal$ )
    (set-face-attribute 'default nil :foreground $normal$ :background $background$)
    (set-face-attribute 'button nil :foreground $keywords$ :underline t)
    (set-face-attribute 'default nil :background $background$ :foreground $normal$)
    (set-face-attribute 'header-line nil :background (Ox33b4O/$/mode-line-background) :foreground $normal$)
    (set-face-attribute 'highlight nil :background $current-line$ :foreground (Ox33b4O/$/mode-line-foreground))
    (set-face-attribute 'info-xref nil :foreground "#27CE79" :underline nil :bold nil)
    (set-face-attribute 'info-xref-visited nil
                        :foreground "#787878"
                        :overline nil
                        :underline "#D87101"
                        :bold t)

    (set-face-attribute 'info-menu-star nil :foreground (Ox33b4O/$/mode-line-foreground) :underline nil :bold t)
    (set-face-attribute 'info-header-xref nil  :foreground $keywords$ :underline t)
    (set-face-attribute 'show-paren-match nil :background (Ox33b4O/$/mode-line-foreground) :foreground $background$ :weight 'bold)
    (set-face-attribute 'show-paren-match-expression nil :background $type-face$  :weight 'bold)
    (set-face-attribute 'show-paren-mismatch nil :background $error$  :foreground $normal$ :weight 'bold)
    (set-face-attribute 'region nil :background $sel$ :foreground $background$)
    (set-face-attribute 'makefile-space nil :background $background$ :foreground $error$)
    (set-face-attribute 'ibuffer-locked-buffer nil :background $warning$ :foreground $background$)
    (set-face-attribute 'separator-line nil :background $background$ :foreground $keywords$ )
    (set-face-attribute 'font-lock-builtin-face nil :foreground $operators$)
    (set-face-attribute 'font-lock-comment-delimiter-face nil :foreground $comments$)
    (set-face-attribute 'font-lock-comment-face nil :foreground $comments$)
    (set-face-attribute 'font-lock-constant-face nil :foreground $constant$)
    (set-face-attribute 'font-lock-doc-face nil :foreground $string$)
    (set-face-attribute 'font-lock-doc-markup-face nil :foreground $string$)
    (set-face-attribute 'font-lock-function-name-face nil :foreground $method-declaration$)
    (set-face-attribute 'font-lock-keyword-face nil :foreground $keywords$)
    (set-face-attribute 'font-lock-negation-char-face nil :foreground $admonition$)
    (set-face-attribute 'font-lock-constant-face nil :foreground $number$)
    (set-face-attribute 'font-lock-preprocessor-face nil :foreground $keywords$)
    (set-face-attribute 'font-lock-constant-face nil :foreground $constant$)
    (set-face-attribute 'font-lock-regexp-grouping-backslash nil :foreground $regexp$)
    (set-face-attribute 'font-lock-regexp-grouping-construct nil :foreground $regexp$)
    (set-face-attribute 'font-lock-string-face nil :foreground $string$)
    (set-face-attribute 'font-lock-type-face nil :foreground $type-face$)
    (set-face-attribute 'font-lock-variable-name-face nil :foreground $variable$)
    (set-face-attribute 'font-lock-warning-face nil :foreground $admonition$ :background $background$)
    (set-face-attribute 'fringe nil :background $background$ :foreground $background$)
    (set-face-attribute 'holiday nil :background $admonition$ :foreground $background$)
    (set-face-attribute 'calendar-weekday-header nil :background $background$ :foreground $mode-line-inactive-bg$)
    ;; (set-face-attribute 'line-number nil :background $background$ :foreground $current-line-number$)
    ;; (set-face-attribute 'line-number-current-line nil :background $current-line-number$ :foreground $background$)
    (set-face-attribute 'line-number nil :background $background$ :foreground $comments$)
    (set-face-attribute 'line-number-current-line nil :background $background$ :foreground $current-line-number$)
    (set-face-attribute 'line-number-major-tick nil :background $background$ :foreground $comments$)
    (set-face-attribute 'line-number-minor-tick nil :background $background$ :foreground $string$)
    (set-face-attribute 'minibuffer-prompt nil :foreground $variable$)
    (set-face-attribute 'rectangle-preview nil :background $line-number$)
    (set-face-attribute 'mode-line nil :background (Ox33b4O/$/mode-line-background) :foreground (Ox33b4O/$/mode-line-foreground))
    (set-face-attribute 'mode-line-inactive nil :background $mode-line-inactive-bg$ :foreground $mode-line-inactive-fg$)
    (set-face-attribute 'mode-line-emphasis nil :bold nil)
    (set-face-attribute 'vertical-border nil)
    (set-face-attribute 'isearch nil :background (Ox33b4O/$/mode-line-foreground) :foreground (Ox33b4O/$/mode-line-background))
    (set-face-attribute 'isearch-fail nil :background $error$ :foreground $background$)
    (set-face-attribute 'error nil :background $error$ :foreground "#333")
    (set-face-attribute 'shadow nil :foreground "#333")
    (set-face-attribute 'fill-column-indicator nil :foreground "#111")
    (set-face-attribute 'warning nil :foreground $warning$ :background $background$)
    (set-face-attribute 'underline :underline)

    (set-face-attribute 'compilation-mode-line-fail nil :background "#EEE" :background "#222")
    (set-face-attribute 'lazy-highlight nil :background $current-line$ :foreground $sel$)
    (when (require 'ert)
      (progn
        (set-face-attribute 'ert-test-result-expected nil :background "#3cc14c" :foreground $background$)
        (set-face-attribute 'ert-test-result-unexpected nil :background $error$ :foreground $background$)
        (set-face-attribute 'escape-glyph nil :background $background$ :foreground $error$)
        (set-face-attribute 'homoglyph nil :background $background$ :foreground $admonition$)
        (set-face-attribute 'fill-column-indicator nil :background $background$)))

    (when
        (require 'web-mode)
      (progn
        (set-face-attribute 'web-mode-json-key-face nil :foreground $keywords$)
        (set-face-attribute 'web-mode-json-string-face nil :foreground $variable$)
        (set-face-attribute 'web-mode-json-context-face nil :foreground "#79B9FF")))

    (when
        (require 'markdown-mode)
      (progn
        (set-face-attribute 'markdown-markup-face nil :foreground $variable$))
      (set-face-attribute 'markdown-link-face nil :foreground "#79B9FF")
      )

    (mapc #'(lambda (s)
              (set-face-attribute s nil :background "#000" :foreground "#000"))
          (list
           'border
           'child-frame-border
           'header-line-highlight
           'internal-border
           'window-divider
           'window-divider-first-pixel
           'window-divider-last-pixel
           'mode-line-highlight))))


(add-hook 'after-init-hook '$$$$$$$$)
(add-hook 'after-save-hook '$$$$$$$$)
($$$$$$$$)
