(defun entrypoint-regexp-fix()
  (let* (
         (time-unit (match-string 8)
                    )
         (arith-display (match-string 6)
                        )
         (arith-unit (match-string 12)
                     )
         (tmp-var-name (format "tmp_%s_with_time_unit" time-unit )
                       )
         (tmp-var-decl (format "%s=%s" tmp-var-name arith-display)
                       )
         (time-parts-new-item (match-string 4)
                              )
         (time-parts-push (format "time_parts+=(\"%s\")" time-parts-new-item )
                          )
         (string-chunk-to-join "          \n")
         ) ;; end varlist
    ;; (lines-list (mapcar (lambda (line)
    ;;                       (format "        %s" line)
    ;;                   )
    ;;                  ) )
    )
  )
